# Build status located at https://travis-ci.org/citra-emu/citra-web

language: node_js

node_js: "node"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - echo '========== Installing gulp & dependencies =========='
  - sudo apt-get install graphicsmagick
  - convert -help
  - yarn global add @alrra/travis-scripts
  - yarn global add hugo-bin
  - hugo version
  - yarn global add gulp

  - echo '========== Configuring Github Pages =========='
  - git config --global user.email "citra+citrabotweb@citra-emu.org"
  - git config --global user.name "CitraBotWeb"
  - set-up-ssh --key "$encrypted_c7ee54b5843f_key" --iv "$encrypted_c7ee54b5843f_iv" --path-encrypted-key "bf215181b5140522137b3d4f6b73544a.enc"

  - echo '========== Starting gulp deploy task =========='
  - gulp deploy all --production

notifications:
  email:
    - mods@citra-emu.org

# set-up-ssh is provided by travis-scripts.
# Setting up the SSH key for Github is described here.
# https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md
