# Build status located at https://travis-ci.org/citra-emu/citra-web

language: node_js
node_js:
  - "lts/erbium"
cache: yarn

script:
  - echo '========== Updating Yarn ==========================='
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - echo '========== Installing gulp & dependencies =========='
  - sudo apt-get install graphicsmagick
  - wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  - yarn install

  - echo '========== Starting gulp deploy task =========='
  - hugo version
  - yarn run gulp all --production
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: build
 repo: CitraBotWeb/CitraBotWeb.github.io
 target_branch: master
 fqdn: citra-emu.org
 on:
   branch: master
notifications:
  email:
    - citra@citra-emu.org
